{
 "title": "Chat",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "AI.Chat.Adapter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai_chat_adapters_reply_length_count{job=\"ai-chat-hosts-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ai_chat_adapters_reply_length_count{job=\"ai-chat-hosts-api\"}[$__range]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tokens",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai_chat_adapters_tokens{job=\"ai-chat-hosts-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Length",
   "type": "histogram",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(le) (ai_chat_adapters_reply_length_bucket{job=\"ai-chat-hosts-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Length",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai_chat_adapters_reply_length_sum{job=\"ai-chat-hosts-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Length Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ai_chat_adapters_reply_length_sum{job=\"ai-chat-hosts-api\"}[$__range]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AI.Chat.Bot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Total Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ai_chat_bots_message_length_count{job=\"ai-chat-hosts-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ai_chat_bots_message_length_count{job=\"ai-chat-hosts-api\"}[$__range]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai_chat_bots_message_length_count{job=\"ai-chat-hosts-api\"}",
     "legendFormat": "{{user_name}}"
    }
   ]
  },
  {
   "title": "Length",
   "type": "histogram",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "expr": "sum by(le) (ai_chat_bots_message_length_bucket{job=\"ai-chat-hosts-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Length",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ai_chat_bots_message_length_sum{job=\"ai-chat-hosts-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Length Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(ai_chat_bots_message_length_sum{job=\"ai-chat-hosts-api\"}[$__range]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "TwitchLib.Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Total Count",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(twitchlib_client_message_length_count{job=\"ai-chat-hosts-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(twitchlib_client_message_length_count{job=\"ai-chat-hosts-api\"}[$__range]))*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 31 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "twitchlib_client_message_length_count{job=\"ai-chat-hosts-api\"}",
     "legendFormat": "{{user_name}}"
    }
   ]
  },
  {
   "title": "Length",
   "type": "histogram",
   "gridPos": { "h": 14, "w": 8, "x": 16, "y": 31 },
   "targets": [
    {
     "expr": "sum by(le) (twitchlib_client_message_length_bucket{job=\"ai-chat-hosts-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Length",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(twitchlib_client_message_length_sum{job=\"ai-chat-hosts-api\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Length Rate",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(twitchlib_client_message_length_sum{job=\"ai-chat-hosts-api\"}[$__range]))*60",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}