{
 "title": "Logs",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "AI.Chat.Clients.Twitch",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"$job\"} | json | instrumentation_scope_name = `AI.Chat.Bots.Diagnostics.Log` | line_format `{{.severity}} {{.body}}`"
    },
    {
     "direction": "backward",
     "expr": "{job=~\"$job\"} | json | instrumentation_scope_name = `AI.Chat.Adapters.Diagnostics.Log` | line_format `{{.severity}} {{.body}}`"
    },
    {
     "direction": "backward",
     "expr": "{job=~\"$job\"} | json | instrumentation_scope_name = `AI.Chat.Filters.Diagnostics.Log` | line_format `{{.severity}} {{.body}}`"
    }
   ]
  },
  {
   "title": "TwitchLib.Client.TwitchClient",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"$job\"} | json | instrumentation_scope_name = `TwitchLib.Client.TwitchClient` | line_format `{{.severity}} {{.body}}`"
    }
   ]
  },
  {
   "title": "AI.Chat.CommandExecutors",
   "type": "logs",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{job=~\"$job\"} | json | instrumentation_scope_name = `AI.Chat.CommandExecutors.Diagnostics.Log` | line_format `{{.severity}} {{.body}}`"
    }
   ]
  }
 ]
}