{
 "title": "Runtime",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(dotnet_assembly_count,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_gc_last_collection_memory_committed_size_bytes{job=~\"$job\"}",
     "legendFormat": "Committed"
    },
    {
     "expr": "sum(dotnet_gc_last_collection_heap_size_bytes{job=~\"$job\"})",
     "legendFormat": "Heap"
    },
    {
     "expr": "sum(dotnet_gc_last_collection_heap_fragmentation_size_bytes{job=~\"$job\"})",
     "legendFormat": "Fragmentation"
    },
    {
     "expr": "dotnet_process_memory_working_set_bytes{job=~\"$job\"}",
     "legendFormat": "Process"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "idelta(dotnet_process_cpu_time_seconds_total{job=~\"$job\"}[$__range]) / ${__interval}",
     "legendFormat": "{{cpu_mode}}"
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_thread_pool_thread_count_total{job=~\"$job\"}",
     "legendFormat": "Threads"
    },
    {
     "expr": "dotnet_thread_pool_queue_length_total{job=~\"$job\"}",
     "legendFormat": "Work Items"
    }
   ]
  },
  {
   "title": "Exceptions",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dotnet_exceptions_total{job=~\"$job\"}",
     "legendFormat": "{{error_type}}"
    }
   ]
  }
 ]
}