name:
  ai-chat-hosts-docker

services:
  ai-chat-hosts-api:
    container_name: ai-chat-hosts-api
    depends_on:
      - alloy
    image: ai.chat.hosts.api
    build:
      context: ../..
      dockerfile: src/AI.Chat.Hosts.API/Dockerfile
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://alloy:4317
      - OTEL_SERVICE_NAME=ai-chat-hosts-api
    volumes:
      - ai.chat.hosts.config:/app/external
    ports:
      - 5117:8080
    networks:
      - ai-chat-hosts-docker

networks:
  ai-chat-hosts-docker:
    external: true

volumes:
  ai.chat.hosts.config:
    external: true
