stream_over_http_enabled: true

server:
  log_level: info
  http_listen_port: 8080
  grpc_listen_port: 8081

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: "0.0.0.0:8082"

storage:
  trace:
    backend: local
    wal:
      path: /data/tempo/wal
    local:
      path: /data/tempo/blocks

backend_scheduler:
  provider:
    compaction:
      compaction:
        block_retention: 72h

backend_worker:
  compaction:
    block_retention: 72h

usage_report:
  reporting_enabled: false
