{
 "title": "Console",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "range" ] } },
   "targets": [
    {
     "expr": "ai_chat_hosts_console_cpu_total",
     "legendFormat": "{{mode}}"
    },
    { "expr": "$__range_s * 1000000000", "legendFormat": "max" }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ai_chat_hosts_console_memory_total",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{__name__=~\"ai_chat_.*_network_total\"}",
     "legendFormat": "{{__name__}} {{type}}"
    }
   ]
  },
  {
   "title": "Twitch",
   "type": "logs",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"ai_chat_hosts_console\"} | json | instrumentation_scope_name = `ai_chat_clients_twitch` | line_format `{{.body}}`"
    }
   ]
  },
  {
   "title": "OpenAI",
   "type": "logs",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"ai_chat_hosts_console\"} | json | instrumentation_scope_name = `ai_chat_adapters_openai` | line_format `{{.body}}`"
    }
   ]
  }
 ]
}