{
 "title": "Scopes",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  { "title": "Read", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traces_spanmetrics_calls_total{source=\"tempo\", span_name=~\"AI[.]Chat[.]Scopes[.].*[.]ExecuteRead.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ai_chat_scopes_read_open_total{job=\"ai-chat-host-api\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ai_chat_scopes_read_close_total{job=\"ai-chat-host-api\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Left Open",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 9, "y": 1 },
   "targets": [
    {
     "expr": "ai_chat_scopes_read_open_total{job=\"ai-chat-host-api\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ai_chat_scopes_read_close_total{job=\"ai-chat-host-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "traces_spanmetrics_latency{source=\"tempo\", span_name=~\"AI[.]Chat[.]Scopes[.].*ExecuteRead.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Write", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Total",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(traces_spanmetrics_calls_total{source=\"tempo\", span_name=~\"AI[.]Chat[.]Scopes[.].*[.]ExecuteWrite.*\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(ai_chat_scopes_write_open_total{job=\"ai-chat-host-api\"}[$__range])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ai_chat_scopes_write_close_total{job=\"ai-chat-host-api\"}[$__range])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Left Open",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 5, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "ai_chat_scopes_write_open_total{job=\"ai-chat-host-api\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "ai_chat_scopes_write_close_total{job=\"ai-chat-host-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distribution",
   "type": "histogram",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 12 },
   "targets": [
    {
     "expr": "traces_spanmetrics_latency{source=\"tempo\", span_name=~\"AI[.]Chat[.]Scopes[.].*ExecuteWrite.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}