name:
  ai-chat-hosts-docker

services:
  loki:
    container_name: loki
    image: grafana/loki:3.7.7
    volumes:
      - ./loki:/etc/loki
      - data.loki:/data
    command: 
      - -config.file=/etc/loki/config.yaml
    networks:
      - ai-chat-hosts-docker

  tempo:
    container_name: tempo
    image: grafana/tempo:3.0.3
    volumes:
      - ./tempo:/etc/tempo
      - data.tempo:/data
    command: 
      - -config.file=/etc/tempo/config.yaml
    networks:
      - ai-chat-hosts-docker

  prometheus:
    container_name: prometheus
    image: prom/prometheus:v3.14.0
    volumes:
      - ./prometheus:/etc/prometheus
      - data.prometheus:/data
    command: 
      - --config.file=/etc/prometheus/config.yaml
      - --storage.tsdb.path=/data
      - --web.listen-address=0.0.0.0:8080
      - --web.enable-otlp-receiver
      - --enable-feature=promql-experimental-functions
      - --enable-feature=otlp-deltatocumulative
    networks:
      - ai-chat-hosts-docker

  alloy:
    container_name: alloy
    depends_on:
      - loki
      - tempo
      - prometheus
    image: grafana/alloy:v1.19.2
    volumes:
      - ./alloy:/etc/alloy
      - data.alloy:/data
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:8080
      - --disable-reporting
      - --storage.path=/data
      - /etc/alloy/config.alloy
    ports:
      - 8080:8080
      - 8081:8081
    networks:
      - ai-chat-hosts-docker

  grafana:
    container_name: grafana
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    depends_on:
      - loki
      - tempo
      - prometheus
    image: grafana/grafana:13.2.1
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    ports:
      - 3000:3000
    networks:
      - ai-chat-hosts-docker

networks:
  ai-chat-hosts-docker:
    external: true

volumes:
  data.loki:
    external: true
  data.tempo:
    external: true
  data.prometheus:
    external: true
  data.alloy:
    external: true
